### ISSUE TITLE
Typing errors Julia_1.6.0.ipynb file

### ISSUE THREAD

**Issue by TetraGenius** [Dsantra92/Julia-on-Colab#12]
preferred & hardware
After you run the first cell (the the cell directly above this text), go to Colab's menu bar and select Edit and select Notebook settings from the drop down. Select Julia 1.6 in Runtime type. You can also select your prefered (preferred) harwdware (hardware) acceleration (defaults to GPU).

Regards,
Theuns

**Comment by Dsantra92** [comment]
Thanks for pointing out! Can you also make a pr to update it?
