### ISSUE TITLE
Consider upgrade to Julia 1.4.2 or 1.5

### ISSUE THREAD

**Issue by PallHaraldsson** [Dsantra92/Julia-on-Colab#4]
[I got working, but not at first, so my experience below reflects that. Thanks for making this!]

I mean I got you first cell working, and also by switching to this line:

```
wget 'https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz' \
```

in both cases I could chose "GPU" (or "TPU", maybe your example could be amended for it), but not Julia, any version, but only in either the original one I found jJulia under:

```
!jupyter kernelspec list
```

just not sure how to enable it.

I managed to copy paste by using this link (or other way, but failed to located simple download... on GitHub):

https://raw.githubusercontent.com/Dsantra92/Julia-on-Colab/master/julia_on_collab.ipynb

I noted installed:
[b85f4697] + SoftGlobalScope v1.0.10

I guess this is the same as in Julia 1.5, one of the reasons to (otherwise) prefer it.

**Comment by Dsantra92** [comment]
Go to the thread https://discourse.julialang.org/t/julia-on-google-colab-free-gpu-accelerated-shareable-notebooks/15319/36
